### ISSUE TITLE
Don't know if intended

### ISSUE THREAD

**Issue by Zero9o1o** [blay09/BalyBot#1]
when you remove a command the ids for the commands don't become free.
example:
if you make a command and it gets id 1 then you unset the command and then make a new command the new command will have the id 2 instead of 1.

**Comment by BlayTheNinth** [comment]
That's just how databases work, IDs aren't re-used. The only thing that should be changed here is to remove the AUTOINCREMENT and just have it use Sqlite's ROWID.

**Comment by BlayTheNinth** [comment]
AUTO_INCREMENT only used for MySQL backend now on multi branch.
