### ISSUE TITLE
Needs a bit more documentation love

### ISSUE THREAD

**Issue by Zero9o1o** [blay09/BalyBot#2]
Some of the modules might be missing config documentation or modules don't have any config options.
The Song module doesn't show and configurations or it doesn't let you change user level for command. Raffle module is the same as song doesn't show a config option in the documentation.

**Comment by Zero9o1o** [comment]
Closing cause it i didn't know the docs for the bot chance depending on what module are enable. suggestion might be to put a text line that says that it does.

**Comment by BlayTheNinth** [comment]
The modules were mostly tests, so only some of them had configurations and some weren't working at all.
